import logging
import random
import time
from typing import Any, Dict, List, Optional

from django.utils import timezone

logger = logging.getLogger(__name__)


def fetch_yfinance_payload(symbol: str) -> Optional[Dict[str, Any]]:
    """
    Fetches live data from Yahoo Finance via yfinance.
    Returns None when yfinance is unavailable or the ticker does not exist.
    """
    try:
        import yfinance as yf
    except ImportError:
        logger.warning('yfinance is not installed; cannot fetch live data')
        return None

    ticker = yf.Ticker(symbol)
    try:
        info = ticker.get_info()
    except Exception as exc:  # pragma: no cover - network call
        logger.error('yfinance get_info failed for %s: %s', symbol, exc)
        return None

    name = info.get('longName') or info.get('shortName') or symbol.upper()
    sector = info.get('sector') or ''
    industry = info.get('industry') or ''
    description = info.get('longBusinessSummary') or ''

    try:
        history_df = ticker.history(period='1mo', interval='1d')
    except Exception as exc:  # pragma: no cover
        logger.error('yfinance history failed for %s: %s', symbol, exc)
        history_df = None

    kline = _history_to_payload(history_df)
    news = _yfinance_news_to_payload(getattr(ticker, 'news', []))

    if not kline and not news:
        logger.info('yfinance returned empty payload for %s', symbol)

    return {
        'symbol': symbol.upper(),
        'name': name,
        'sector': sector,
        'industry': industry,
        'description': description,
        'daily_kline': kline,
        'news': news,
    }


def build_sample_payload(symbol: str, metadata: Dict[str, Any] | None = None) -> Dict[str, Any]:
    """
    Generates a deterministic sample payload that mimics data retrieved from an external crawler.
    The payload is fed into Neo4j so that the single stock page has realistic demo content.
    """
    random.seed(symbol)
    base_price = 80 + random.random() * 30
    kline = _generate_kline_series(base_price, count=10)
    news = _generate_sample_news(symbol, metadata or {})

    return {
        'symbol': symbol.upper(),
        'name': metadata.get('name') if metadata else f'{symbol.upper()} Corp',
        'sector': (metadata or {}).get('sector', 'Technology'),
        'industry': (metadata or {}).get('industry', 'AI Infrastructure'),
        'description': (metadata or {}).get(
            'description',
            f'{symbol.upper()} is a synthetic stock generated by the crawler demo.',
        ),
        'daily_kline': kline,
        'news': news,
    }


def _history_to_payload(history_df) -> List[Dict[str, Any]]:
    if history_df is None or history_df.empty:
        return []
    points: List[Dict[str, Any]] = []
    for index, row in history_df.tail(30).iterrows():
        timestamp = int(index.timestamp()) if hasattr(index, 'timestamp') else int(time.time())
        points.append(
            {
                'timestamp': timestamp,
                'open': float(row.get('Open', 0)),
                'high': float(row.get('High', 0)),
                'low': float(row.get('Low', 0)),
                'close': float(row.get('Close', 0)),
                'volume': int(row.get('Volume', 0)),
            }
        )
    return points


def _yfinance_news_to_payload(news_items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    payload: List[Dict[str, Any]] = []
    for idx, item in enumerate(news_items or []):
        payload.append(
            {
                'id': item.get('uuid') or f'news-{idx}',
                'title': item.get('title', ''),
                'url': item.get('link') or item.get('url', ''),
                'source': item.get('publisher', ''),
                'published_at': int(item.get('providerPublishTime') or item.get('published_at') or 0),
            }
        )
    return payload


def _generate_kline_series(base_price: float, count: int) -> List[Dict[str, Any]]:
    points = []
    ts = int(time.time()) - count * 86400
    price = base_price
    for _ in range(count):
        delta = random.uniform(-2, 2)
        open_price = max(price + random.uniform(-1, 1), 1)
        close_price = max(open_price + delta, 0.1)
        high = max(open_price, close_price) + random.random()
        low = min(open_price, close_price) - random.random()
        points.append(
            {
                'timestamp': ts,
                'open': round(open_price, 2),
                'close': round(close_price, 2),
                'high': round(high, 2),
                'low': round(low, 2),
                'volume': random.randint(500_000, 2_000_000),
            }
        )
        ts += 86400
        price = close_price
    return points


def _generate_sample_news(symbol: str, metadata: Dict[str, Any]) -> List[Dict[str, Any]]:
    source = metadata.get('source') or 'M7 Research'
    return [
        {
            'id': f'{symbol}-news-{idx}',
            'title': f'{symbol.upper()} Update #{idx + 1}',
            'url': metadata.get('news_url') or f'https://news.example.com/{symbol}/{idx}',
            'source': source,
            'published_at': int(time.time()) - idx * 3600,
        }
        for idx in range(3)
    ]
