#!/usr/bin/env python3
"""
Merge GraphQL schema files from subdirectories into a single schema.graphql.

Usage:
    python merge_schema.py
    
Output:
    libs/schema/schema.graphql (overwritten)

Dependencies are resolved by file order:
    1. common/*.graphql (base types)
    2. news/*.graphql (NewsItem used by market)
    3. market/*.graphql (depends on news)
    4. query.graphql (root Query, depends on all)
"""

from pathlib import Path
from datetime import datetime

SCHEMA_DIR = Path(__file__).parent
OUTPUT_FILE = SCHEMA_DIR / "schema.graphql"

# Order matters: common → news → market → query
DOMAIN_ORDER = ["common", "news", "market"]


def collect_graphql_files() -> list[tuple[str, Path]]:
    """Collect .graphql files in dependency order."""
    files: list[tuple[str, Path]] = []
    
    # 1. Domain subdirectories
    for domain in DOMAIN_ORDER:
        domain_dir = SCHEMA_DIR / domain
        if domain_dir.is_dir():
            for gql_file in sorted(domain_dir.glob("*.graphql")):
                files.append((domain, gql_file))
    
    # 2. Root query.graphql (must be last)
    query_file = SCHEMA_DIR / "query.graphql"
    if query_file.exists():
        files.append(("root", query_file))
    
    return files


def merge_schemas(files: list[tuple[str, Path]]) -> str:
    """Merge all schema files into a single string."""
    header = f"""\
# GraphQL Schema (SSOT)
# Auto-generated by merge_schema.py at {datetime.now().isoformat()}
# DO NOT EDIT DIRECTLY - modify domain files in common/, market/, news/

"""
    sections: list[str] = [header]
    
    for domain, path in files:
        content = path.read_text().strip()
        if not content:
            continue
        sections.append(f"# === {domain.upper()}: {path.name} ===\n")
        sections.append(content)
        sections.append("\n\n")
    
    return "".join(sections).rstrip() + "\n"


def main() -> None:
    files = collect_graphql_files()
    if not files:
        print("No .graphql files found in subdirectories")
        return
    
    merged = merge_schemas(files)
    OUTPUT_FILE.write_text(merged)
    
    print(f"✅ Merged {len(files)} files into {OUTPUT_FILE}")
    for domain, path in files:
        print(f"   - {domain}/{path.name}")


if __name__ == "__main__":
    main()

