# Generated by Django 5.2.8 on 2025-11-21 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('symbol', models.CharField(help_text='Stock ticker symbol', max_length=10, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, help_text='Brief company description', null=True)),
                ('sector', models.CharField(blank=True, help_text='Industry sector', max_length=255, null=True)),
                ('industry', models.CharField(blank=True, help_text='Specific industry', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_ratio', models.FloatField(blank=True, help_text='Price-to-Sales Ratio', null=True)),
                ('pe_ratio', models.FloatField(blank=True, help_text='Price-to-Earnings Ratio', null=True)),
                ('pb_ratio', models.FloatField(blank=True, help_text='Price-to-Book Ratio', null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valuation', to='stock_research.companyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.FloatField(blank=True, help_text='Earnings Per Share', null=True)),
                ('fcf', models.FloatField(blank=True, help_text='Free Cash Flow', null=True)),
                ('current_ratio', models.FloatField(blank=True, help_text='Current Ratio', null=True)),
                ('roe', models.FloatField(blank=True, help_text='Return on Equity', null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='stock_research.companyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(help_text='Stock ticker symbol', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Full company name', max_length=255, null=True)),
                ('exchange', models.CharField(blank=True, help_text='Exchange where the stock is traded', max_length=50, null=True)),
                ('currency', models.CharField(blank=True, help_text='Currency of the stock', max_length=10, null=True)),
                ('company_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='stock_research.companyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EarningData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_date_end', models.DateField(help_text='Fiscal period end date')),
                ('reported_eps', models.FloatField(blank=True, help_text='Reported EPS', null=True)),
                ('estimated_eps', models.FloatField(blank=True, help_text='Estimated EPS', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='stock_research.companyinfo')),
            ],
            options={
                'unique_together': {('company', 'fiscal_date_end')},
            },
        ),
        migrations.CreateModel(
            name='KLineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Unix timestamp of the data point')),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k_lines', to='stock_research.stock')),
            ],
            options={
                'unique_together': {('stock', 'timestamp')},
            },
        ),
    ]
