# Generated by Django 5.2.8 on 2025-11-30 09:14

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerTaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(max_length=50)),
                ('target_symbols', models.JSONField(blank=True, default=list)),
                ('schedule_cron', models.CharField(blank=True, max_length=100)),
                ('status', django_fsm.FSMField(default='pending', max_length=50, protected=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crawler Task',
                'verbose_name_plural': 'Crawler Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataBatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('neo4j_uid', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(max_length=50)),
                ('data_type', models.CharField(max_length=50)),
                ('record_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('status', django_fsm.FSMField(default='raw', max_length=50, protected=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Batch',
                'verbose_name_plural': 'Data Batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
